html form Voichenko Denys
mate-academy/layout_html-form pull request #1032
Opened 2021-09-12 16:25 UTC by DenCoderok

2021-09-14 08:27 UTC, mykola-yarchuk requested changes
в readme файлі потрібно додати demo link 
https://mate-academy.github.io/layout_task-guideline/ - інструкція

2021-09-14 18:16 UTC, DenCoderok commented
https://dencoderok.github.io/layout_html-form/
надеюсь все сделал правильно)

2021-09-16 19:11 UTC, DenCoderok commented
[DEMO LINK](https://dencoderok.github.io/layout_html-form/src/index.html?_ijt=pu760p96ireesub75p6icjdm24)

2021-09-20 14:31 UTC, varseniuk requested changes
По коду особливих зауважень на перший погляд немає, але щоб остаточно в цьому переконатись, було б добре додати лінк на test report

<img width="1388" alt="Снимок экрана 2021-09-20 в 17 29 58" src="https://user-images.githubusercontent.com/66570142/134020212-f6801067-ac9c-4a5b-8e17-491318c6b379.png">

2021-09-25 12:40 UTC, closed without merging