Develop2
mate-academy/layout_html-form pull request #1169
Opened 2021-11-16 13:34 UTC by luckdenny

[DEMO LINK](https://luckdenny.github.io/layout_html-form/)
[TEST REPORT LINK](https://luckdenny.github.io/layout_html-form/report/html_report/)

2021-11-16 17:54 UTC, danheim requested changes

2021-11-16 17:54 UTC, danheim commented on src/index.html
> +            id="sur" required
не сокращай слова, выполни все требования из чек-листа

2021-11-16 20:17 UTC, luckdenny commented on src/index.html
> +            id="sur" required
Thank's, fixed )

2021-11-17 09:54 UTC, danheim requested changes
У тебя в коде не все атрибуты выставлены согласно чек-листу

2021-11-17 09:54 UTC, danheim commented on src/index.html
> +        </div>
переносить нужно каждый атрибут
```suggestion
          <label for="name"> Name:</label>
          <input
            type="text"
            name="Name"
            id="name"
            required
          >
        </div>
```

2021-11-17 11:23 UTC, Elena-brv requested changes

2021-11-17 11:23 UTC, Elena-brv commented on src/index.html
> +    >
checklist

2021-11-17 11:23 UTC, Elena-brv commented on src/index.html
> +          >No
- formatting
- why only 1 label?

2021-11-17 11:23 UTC, Elena-brv commented on src/style.css
> +.inputs-block {
```suggestion
.inputs-block {
```

2021-11-17 12:35 UTC, Elena-brv approved these changes

2021-11-17 12:35 UTC, Elena-brv commented on src/index.html
> +          No
formatting

2021-11-18 22:33 UTC, closed without merging