Solution
mate-academy/layout_html-form pull request #1196
Opened 2021-11-21 22:53 UTC by Anna-Danylko

там где цвета -цвета не показывает..не знаю как это изменить

2021-11-23 12:05 UTC, vkryvytskyy requested changes
Не забывай оставлять ссылку на demo page в описании pr/ или в файле readme.md

2021-11-23 12:05 UTC, vkryvytskyy commented on src/index.html
> +          required>
```suggestion
          <input 
            type="text"
            name="surname"
            id="surname"
            required
          >
```
Форматируй теги таким образом

2021-11-23 12:05 UTC, vkryvytskyy commented on src/index.html
> +          </select>
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color

2021-12-01 12:30 UTC, Anna-Danylko commented
https://Anna-Danylko.github.io/layout_html-form/
https://Anna-Danylko.github.io/layout_html-form/report/html_report/

2022-04-19 06:25 UTC, Bohdan-Maksymiuk requested changes
https://github.com/mate-academy/layout_html-form/blob/master/checklist.md
пройдися по чеклисту і виправ у всіх місцях

2022-04-19 06:25 UTC, Bohdan-Maksymiuk commented on src/index.html
> +          autocomplete="off">
```suggestion
          <textarea
            type="text"
            name="comments" id="comments"
            rows="3"
            cols="15"
            autocomplete="off"
          >
```

2022-04-19 06:25 UTC, Bohdan-Maksymiuk commented on src/index.html
> +          >
```suggestion
          <input
            type="range"
            name="rate"
            id="rate"
            min="0"
            max="10"
          >
```

2022-04-19 06:25 UTC, Bohdan-Maksymiuk commented on src/index.html
> +          name="cars" id="cars">
```suggestion
          <select
            multiple
            name="cars"
            id="cars"
          >
```

2022-05-05 16:47 UTC, closed without merging