Develop
mate-academy/layout_html-form pull request #1286
Opened 2021-12-28 16:24 UTC by IBzot

2021-12-29 17:49 UTC, aliceblunt8 requested changes
please add demo link and test link
and deploy your project if you hadn't done it before

2021-12-30 13:02 UTC, varseniuk requested changes
Досі немає DEMO LINK та TEST REPORT LINK

2021-12-30 13:17 UTC, IBzot commented
https://<your_account>.github.io/layout_html-form/
https://<your_account>.github.io/layout_html-form/report/html_report/

2021-12-30 13:24 UTC, IBzot commented
https://IBzot.github.io/layout_html-form/
https://Ibzot.github.io/layout_html-form/report/html_report/

2021-12-30 13:29 UTC, varseniuk requested changes
Лінки не працюють. Ти запускав npm run deploy?
![image](https://user-images.githubusercontent.com/66570142/147756270-4dddf1af-30b8-46a9-a483-0d5d2cad8868.png)

2021-12-30 19:29 UTC, IBzot commented
Заходжу в github > settings > pages  і пише There are no verified domains.

2021-12-30 19:59 UTC, IBzot commented
![image](https://user-images.githubusercontent.com/96305433/147784333-2a0b3c6f-3f7d-4f4c-a8c5-095333bde4ca.png)

2022-01-10 14:54 UTC, IBzot commented
Як запустити run deploy ? Заходжу в github > settings > pages і пише There are no verified domains.
 роблю як в інстр. 
 github > settings > pages і пише There are no verified domains.

2022-01-13 13:20 UTC, closed without merging