Develop
mate-academy/layout_html-form pull request #1305
Opened 2022-01-16 20:07 UTC by AndrejGutnik

https://AndrejGutnik.github.io/layout_html-form/
https://AndrejGutnik.github.io/layout_html-form/report/html_report/

2022-01-17 17:28 UTC, vkryvytskyy reviewed
Поправь форматирование и стилизуй через классы

2022-01-17 17:28 UTC, vkryvytskyy commented on readme.md
> +- [DEMO LINK](https://AndrejGutnik.github.io/layout_html-form/)
![image](https://user-images.githubusercontent.com/38065883/149814407-2aeef6db-096f-4eaa-9ef9-b3b184df031c.png)
Вряд ли я могу и любить и не любить котов одновременно

2022-01-17 17:28 UTC, vkryvytskyy commented on src/index.html
> +          >
```suggestion
          <input
            type="text"
            id="surname"
            name="userSurname"
            autocomplete="off"
          >
```
Добавляй отступы атрибутам

2022-01-17 17:28 UTC, vkryvytskyy commented on src/style.css
> +fieldset {
Добавь этим элементам классы, и стилизуй используя классы

2022-01-17 17:29 UTC, vkryvytskyy requested changes
пофикси комментарии

2022-01-17 20:04 UTC, AndrejGutnik commented
исправил все

2022-01-19 20:33 UTC, AndrejGutnik commented on src/style.css
> +fieldset {
исправил все

2022-01-27 20:12 UTC, closed without merging