solution
mate-academy/layout_html-form pull request #1352
Opened 2022-01-29 15:01 UTC by AntonFof

- [DEMO LINK](https://AntonFof.github.io/layout_html-form/)
- [TEST REPORT LINK](https://AntonFof.github.io/layout_html-form/report/html_report/)

2022-01-31 12:16 UTC, vkryvytskyy requested changes
Поправь форматирование

2022-01-31 12:16 UTC, vkryvytskyy commented on src/index.html
> +          </label>
```suggestion
          <label for="surname">
            Surname:
          </label>
```
Два отступа

2022-01-31 12:16 UTC, vkryvytskyy commented on src/index.html
> +          >
```suggestion
          <input
            type="text"
            name="surname"
            id="surname"
            autocomplete="off"
          >
```

2022-01-31 12:16 UTC, vkryvytskyy commented on src/index.html
> +          </label>
```suggestion
          <label for="no">
            No
          </label>
```

2022-01-31 12:16 UTC, vkryvytskyy commented on src/index.html
> +
```suggestion

```

2022-02-05 16:16 UTC, AntonFof commented on src/index.html
> +
Форматирование исправлено

2022-02-12 16:25 UTC, closed without merging

2022-02-14 12:00 UTC, varseniuk reviewed
Неможливо апрувнути роботу, так як плу-реквест закритий