html form
mate-academy/layout_html-form pull request #1517
Opened 2022-03-29 13:59 UTC by ISRLv2021

- [DEMO LINK](https://ISRLv2021.github.io/layout_html-form/)
- [TEST REPORT LINK](https://ISRLv2021.github.io/layout_html-form/report/html_report/)

2022-03-29 15:44 UTC, Denchepornyuk requested changes

2022-03-29 15:44 UTC, Denchepornyuk commented on src/index.html
> +        </label>
you can remove `for` and `id` attributes because input is inside the label, fix in all places

2022-03-29 15:44 UTC, Denchepornyuk commented on src/index.html
> +        <label for="dateOfBirth" class="label">
```suggestion
        <label for="date-of-birth" class="label">
```

2022-03-29 15:44 UTC, Denchepornyuk commented on src/index.html
> +        </label>
don't use one label for two inputs, create separate labels for each input

2022-03-29 15:44 UTC, Denchepornyuk commented on src/index.html
> +            <option value="BMW">BMW</option>
Why are values `BWM` for every option?

2022-03-29 20:42 UTC, ISRLv2021 commented on src/index.html
> +        </label>
ok, thank you a lot

2022-03-29 21:08 UTC, ISRLv2021 commented on src/index.html
> +        </label>
I did it, but with one extra css class

2022-03-29 21:09 UTC, ISRLv2021 commented on src/index.html
> +            <option value="BMW">BMW</option>
got it, thanks

2022-03-30 12:34 UTC, Denchepornyuk approved these changes

2022-03-30 12:34 UTC, Denchepornyuk commented on src/index.html
> +                Yes
```suggestion
              Yes
```

2022-03-30 12:34 UTC, Denchepornyuk commented on src/index.html
> +                No
```suggestion
              No
```

2022-03-30 12:47 UTC, ISRLv2021 commented on src/index.html
> +                No
Understandable, thank you

2022-12-21 21:24 UTC, closed without merging