html-form
mate-academy/layout_html-form pull request #1547
Opened 2022-04-12 12:16 UTC by vitalii-heiko

- [DEMO LINK](https://vitalii-heiko.github.io/layout_html-form/)
- [TEST REPORT LINK](https://vitalii-heiko.github.io/layout_html-form/report/html_report/)

2022-04-12 14:20 UTC, ArturErmolenko requested changes
Check all ident and you don't need use tag <br>

2022-04-12 14:20 UTC, ArturErmolenko commented on src/index.html
> +          required
```suggestion
          <input 
            class="form-field-input" 
            type="text" 
            autocomplete="off" 
            name="surname" 
            required
```

2022-04-12 14:20 UTC, ArturErmolenko commented on src/index.html
> +          ><br>
Check ident

2022-04-12 14:20 UTC, ArturErmolenko commented on src/index.html
> +          required
same check ident

2022-04-12 14:20 UTC, ArturErmolenko commented on src/index.html
> +          >
```suggestion
          <input 
            type="range" 
            value="0" 
            name="rate-work"
          >
```

2022-04-12 14:20 UTC, ArturErmolenko commented on src/index.html
> +          name="comments"
ident

2022-04-12 15:44 UTC, vitalii-heiko commented on src/index.html
> +          required
please russian. i don`t understand

2022-04-12 19:17 UTC, vkryvytskyy requested changes

2022-04-12 19:17 UTC, vkryvytskyy commented on readme.md
> +- [DEMO LINK](https://vitalii-heiko.github.io/layout_html-form/)
https://user-images.githubusercontent.com/38065883/163036691-76519cb1-409f-4e31-a51b-08f06f4624c1.mov

При клике на текст должно фокусироваться соответствующее поле
Вот скрин из условия
<img width="639" alt="image" src="https://user-images.githubusercontent.com/38065883/163036807-23eaff18-9e33-4803-be21-f2ebd91fb908.png">

2022-04-12 19:17 UTC, vkryvytskyy commented on src/index.html
> +          ><br>
```suggestion
          >
          <br>
```
Один тег - одна линия

2022-04-12 19:17 UTC, vkryvytskyy commented on src/index.html
> +        <label for="surname">
Для того чтобы связать лейбл с полем - у поля должен быть установлен атрибут id

2022-04-12 19:17 UTC, vkryvytskyy commented on src/index.html
> +
```suggestion
```
Не надо делать такие большие отступы

2022-04-12 19:17 UTC, vkryvytskyy commented on src/index.html
> +         ></textarea><br>
```suggestion
         ></textarea>
         <br>
```

2022-04-12 19:23 UTC, vkryvytskyy requested changes
Нажимай кнопку `re-request review` только после того как сделаешь коммит с изменениями. Пока никаких изменений нет

2022-04-13 15:31 UTC, closed without merging

2022-04-13 19:50 UTC, ArturErmolenko approved these changes