1st-commit
mate-academy/layout_html-form pull request #1725
Opened 2022-06-01 19:38 UTC by pavel-gutsal

1rst-commit

2022-06-02 14:12 UTC, pavel-gutsal commented
working form (sort of)
https://pavel-gutsal.github.io/layout_html-form/
https://pavel-gutsalt.github.io/layout_html-form/report/html_report/

2022-06-02 14:53 UTC, aliceblunt8 requested changes
only one option can be chosen at a time, also by clicking on the label yes or no the corresponding option should be marked

<img width="282" alt="Screenshot 2022-06-02 at 17 52 07" src="https://user-images.githubusercontent.com/57598825/171657614-a24152bb-4a1f-4835-a24d-87d1459914dc.png">

2022-06-02 14:53 UTC, aliceblunt8 commented on src/index.html
> +            value="no"
name should be the same

2022-06-02 15:01 UTC, pavel-gutsal commented on src/index.html
> +            value="no"
fixed

2022-06-02 15:03 UTC, pavel-gutsal commented
https://pavel-gutsal.github.io/layout_html-form/

2022-06-02 18:50 UTC, pavel-gutsal commented
TEST REPORT LINK is operational . I made a typo initially and didn`t noticed it.

2022-06-03 10:04 UTC, aliceblunt8 approved these changes

2022-10-07 11:04 UTC, closed without merging