Form
mate-academy/layout_html-form pull request #1966
Opened 2022-07-18 10:19 UTC by F-u-n-H-o-u-s-e

2022-07-18 10:19 UTC, F-u-n-H-o-u-s-e commented
Form.

2022-07-19 12:57 UTC, ArturErmolenko requested changes
Check your code formatting(look at Good Example)
<img width="1178" alt="formatting" src="https://user-images.githubusercontent.com/94292654/179755568-c3ad1d0d-a07c-490d-83ff-8fe1099206aa.png">

2022-07-19 12:57 UTC, ArturErmolenko commented on readme.md
> +- [TEST REPORT LINK](https://F-u-n-H-o-u-s-e.github.io/layout_html-form/report/html_report/)
don't forget to add this links in your PR description

2022-07-19 12:57 UTC, ArturErmolenko commented on src/index.html
> +          class="inputs" max = "100">
```suggestion
          <input
            autocomplete="off" 
            type="number" 
            name="Old"
            value="12" 
            maxlength="3"
            id="Old" 
            min = "1"
            class="inputs"
            max = "100"
           >
```

2022-07-19 12:57 UTC, ArturErmolenko commented on src/index.html
> +          Yes
```suggestion
          <input 
            autocomplete="off" 
            type="radio" 
            name="PetsY" 
          > 
            Yes
```

2022-07-20 04:53 UTC, F-u-n-H-o-u-s-e commented
Okey, thank you.

2022-07-21 09:53 UTC, F-u-n-H-o-u-s-e commented
DEMO LINK
TEST REPORT LINK

2022-07-27 03:52 UTC, closed without merging