Was added form
mate-academy/layout_html-form pull request #2004
Opened 2022-07-27 11:36 UTC by kmp93

- [DEMO LINK](https://kmp93.github.io/layout_html-form/)
- [TEST REPORT LINK](https://kmp93.github.io/layout_html-form/report/html_report/)

2022-08-01 11:51 UTC, valerii-derkach requested changes
Your demo link doesn't work
and on submit there is an error

2022-08-01 11:51 UTC, valerii-derkach commented on src/index.html
> +            type="text"
```suggestion
            type="date"
```

2022-08-01 11:51 UTC, valerii-derkach commented on src/index.html
> +    <form action="http://localhost:8080/" method="post">
```suggestion
    <form action="https://mate-academy-form-lesson.herokuapp.com/create-application" method="post">
    
```
Please, read the task
On form submit send form data to https://mate-academy-form-lesson.herokuapp.com/create-application

2022-08-05 19:47 UTC, closed without merging

2022-08-05 19:48 UTC, kmp93 commented
New