Develop
mate-academy/layout_html-form pull request #2078
Opened 2022-08-10 15:04 UTC by aleksandr-mazur

https://aleksandr-mazur.github.io/layout_html-form/
https://aleksandr-mazur.github.io/layout_html-form/report/html_report/

2022-08-15 10:00 UTC, stanislav-topikha requested changes
it shouldn't work this way
yes or not, not both
<img width="234" alt="Screenshot 2022-08-15 at 12 52 32" src="https://user-images.githubusercontent.com/99331793/184614886-a1e7e8d8-66cd-4e25-9cb0-2ea564f030d0.png">

2022-08-15 10:00 UTC, stanislav-topikha commented on src/style.css
> +}
[no tag styling ](https://github.com/mate-academy/layout_html-form/blob/master/checklist.md#:~:text=%5BCODE%20STYLE%5D%20%2D%20Don%27t%20style%20tags%2C%20use%20class%20selector%20instead)

2022-08-19 13:05 UTC, valerii-derkach requested changes
please fix identantions
[checklist ](https://github.com/mate-academy/layout_html-form/blob/master/checklist.md)2,3

2022-08-19 13:05 UTC, valerii-derkach commented on src/index.html
> +          >
```suggestion
          E-mail:
          <input
            type="email"
            name="email" 
            placeholder ="email@example.com"
          >
```

2022-08-19 13:05 UTC, valerii-derkach commented on src/index.html
> +          >
```suggestion
          <input
            type="password"
            name="password"
            minlength="8"
          >
```

2022-08-19 13:05 UTC, valerii-derkach commented on src/index.html
> +        </label>
```suggestion
      <label class="input">
          Do you love cats?
          <label>
            <input
              type="radio"
              name="cats"
              value="yes"
            >
            Yes
          </label>

          <label>
            <input
              type="radio"
              name="cats"
              value="no"
            >
            No
          </label>
        </label>
```
<img width="319" alt="image" src="https://user-images.githubusercontent.com/102413088/185623929-3f1a11df-a5ab-4ae6-83ba-bab9a3a705f2.png">

2022-08-19 13:05 UTC, valerii-derkach commented on src/index.html
> +        </label>
same here

2022-08-19 13:05 UTC, valerii-derkach commented on src/index.html
> +          >
same here

2022-08-25 12:43 UTC, liliia-livandovskaya reviewed
Still no fix on this. There should be yes or no
<img width="433" alt="Знімок екрана 2022-08-25 о 15 42 10" src="https://user-images.githubusercontent.com/104769168/186667612-ed95090d-532f-4861-a047-00691923d30b.png">

2022-08-25 12:43 UTC, liliia-livandovskaya commented on src/index.html
> +    <!-- <h1>HTML Form</h1> -->
remove comments

2022-08-25 12:44 UTC, liliia-livandovskaya requested changes
GJ! Make final fixes

2022-08-31 09:47 UTC, closed without merging