Develop
mate-academy/layout_html-form pull request #2492
Opened 2022-10-13 14:57 UTC by Mar4enkofff

https://Mar4enkofff.github.io/layout_html-form/
https://Mar4enkofff.github.io/layout_html-form/report/html_report/

2022-10-16 07:14 UTC, SanyaBratashchuk requested changes

2022-10-16 07:14 UTC, SanyaBratashchuk commented on src/index.html
>      <h1>HTML Form</h1>
```suggestion
```

2022-10-16 07:14 UTC, SanyaBratashchuk commented on src/index.html
> +              name="head"
```suggestion
              name="color"
```

2022-10-16 07:14 UTC, SanyaBratashchuk commented on src/index.html
> +              name="head"
fix `names`

2022-10-16 07:14 UTC, SanyaBratashchuk commented on src/index.html
> +              required>
```suggestion
            <select
              name="recommend"
              required
            >
```

2022-10-17 11:42 UTC, closed without merging

2022-10-17 13:27 UTC, alexandra-protyanova commented
do not close your pr, I can't review it when it closed

2022-10-17 13:28 UTC, alexandra-protyanova commented
<img width="346" alt="Снимок экрана 2022-10-17 в 16 27 59" src="https://user-images.githubusercontent.com/102182808/196189463-7698b2a3-bad6-45ff-8531-b1ffc14fd5dc.png">
Open pr and click here to ask for review

2022-10-17 13:44 UTC, Mar4enkofff commented
how to open it? if the button is not active more?

пн, 17 жовт. 2022 р. о 16:28 Alexandra Protyanova ***@***.***>
пише:

> [image: Снимок экрана 2022-10-17 в 16 27 59]
> <https://user-images.githubusercontent.com/102182808/196189463-7698b2a3-bad6-45ff-8531-b1ffc14fd5dc.png>
> Open pr and click here to ask for review
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mate-academy/layout_html-form/pull/2492#issuecomment-1280861550>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3I5CAK2RMNEJQYQ5VK5UXLWDVIAFANCNFSM6AAAAAAREL2FBY>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2022-10-17 13:45 UTC, Mar4enkofff commented
> <img alt="Снимок экрана 2022-10-17 в 16 27 59" width="346" src="https://user-images.githubusercontent.com/102182808/196189463-7698b2a3-bad6-45ff-8531-b1ffc14fd5dc.png">
> 
> Open pr and click here to ask for review

how to open here if the button is not more active?