It was hard but i did it
mate-academy/layout_html-form pull request #2494
Opened 2022-10-13 18:37 UTC by VasilPan

2022-10-16 08:25 UTC, SanyaBratashchuk requested changes
check your code style with [checklist](https://github.com/mate-academy/layout_html-form/blob/master/checklist.md)

2022-10-16 08:25 UTC, SanyaBratashchuk commented on src/index.html
> +          >
```suggestion
          <input type="text" name="perinfo">
```

2022-10-16 08:25 UTC, SanyaBratashchuk commented on src/index.html
> +          >
Fix it everywhere

2022-10-16 08:25 UTC, SanyaBratashchuk commented on src/index.html
> +          >
```suggestion
          <input 
            type="number"
            name="perinfo"
            min="0"
            max="100"
            value="12"
            autocomplete="off"
          >
```

2022-10-16 08:25 UTC, SanyaBratashchuk commented on src/index.html
> +          >
Fix it everywhere

2022-10-16 08:25 UTC, SanyaBratashchuk commented on src/style.css
> +}
```suggestion
.mainelement {
  margin-bottom: 20px;
}
```

2022-10-16 08:25 UTC, SanyaBratashchuk commented on src/index.html
> +        </lable>
`lable` ?

2022-10-16 08:25 UTC, SanyaBratashchuk commented on src/index.html
> +        <label name="perinfo" class="one">
```suggestion
        <label name="perinfo" class="label">
```

2022-10-16 08:25 UTC, SanyaBratashchuk commented on src/index.html
> +      <fieldset class="mainelement">
```suggestion
      <fieldset class="group">
```

2022-10-19 06:22 UTC, alexandra-protyanova requested changes
add demo and test report link to your pull request

2022-10-21 17:55 UTC, SanyaBratashchuk requested changes
Fix previous comments. If you have any questions feel free to ask in fe_chat1 in Slack

2022-10-21 17:55 UTC, SanyaBratashchuk commented on src/index.html
> +        <label name="perinfo" class="one">
fix it

2022-10-21 17:55 UTC, SanyaBratashchuk commented on src/index.html
> +          >
Fix it

2022-10-21 17:55 UTC, SanyaBratashchuk commented on src/index.html
> +      <fieldset class="mainelement">
fix it

2022-10-23 08:51 UTC, SanyaBratashchuk requested changes
I don't see any changes since last review

2022-10-24 15:33 UTC, closed without merging