last
mate-academy/layout_html-form pull request #2574
Opened 2022-10-25 11:14 UTC by VasilPan

-[DEMO LINK](https://VasilPan.github.io/layout_html-form/)
- [TEST REPORT LINK](https://VasilPan.github.io/layout_html-form/report/html_report/)

2022-10-25 19:49 UTC, stanislav-topikha requested changes
remove white spaces from textarea
<img width="235" alt="image" src="https://user-images.githubusercontent.com/99331793/197868069-50fc0625-d46a-4faa-a024-d9420fdc0752.png">

fix this 

https://user-images.githubusercontent.com/99331793/197868160-47c93144-6fa9-4167-b38b-114c7b6559fa.mov

2022-10-28 18:46 UTC, SanyaBratashchuk requested changes
Check your codestyle with [checklist](https://github.com/mate-academy/layout_html-form/blob/master/checklist.md)

2022-10-28 18:46 UTC, SanyaBratashchuk commented on src/index.html
> +        </label>
```suggestion
          <input
            type="text"
            name="surname"
          >
        </label>
```

2022-10-28 18:46 UTC, SanyaBratashchuk commented on src/index.html
> +          >
```suggestion
          <input
            type="text"
            name="name"
          >
```

2022-10-28 18:46 UTC, SanyaBratashchuk commented on src/index.html
> +          >
```suggestion
          <input
            type="number"
            name="age"
            min="0"
            max="100"
            value="12"
            autocomplete="off"
          >
```

2023-01-04 08:39 UTC, closed without merging