added html form
mate-academy/layout_html-form pull request #2586
Opened 2022-10-26 10:20 UTC by Vitalii-Fediaiev

[DEMO LINK](https://vitalii-fediaiev.github.io/layout_html-form/)
[TEST REPORT LINK](https://vitalii-fediaiev.github.io/layout_html-form/report/html_report/)

2022-10-26 12:18 UTC, liliia-livandovskaya commented on src/style.css
> +}
add one empty field in the end

2022-10-26 12:18 UTC, liliia-livandovskaya commented on src/style.css
>  /* styles go here */
remove comments

2022-10-26 12:18 UTC, liliia-livandovskaya commented on src/index.html
> +          </textarea>
```suggestion
          <textarea
           required 
           name="feedback"
           minlength="1"
           maxlength="5">
          </textarea>
```

2022-10-26 12:19 UTC, liliia-livandovskaya commented on src/index.html
> +             name="time">
```suggestion
          <input
             type="time" 
             name="time"
           >
```
fix code style all over the page

2022-10-26 12:19 UTC, liliia-livandovskaya requested changes
GJ! Pay attention to comments and checklist

2022-10-27 17:02 UTC, liliia-livandovskaya commented on src/style.css
> +}
add one more empty line in the end

2022-10-27 17:02 UTC, liliia-livandovskaya commented on src/index.html
> +
```suggestion
```

2022-10-27 17:03 UTC, liliia-livandovskaya commented on src/index.html
> +
add name atribute

2022-10-27 17:03 UTC, liliia-livandovskaya commented on src/index.html
> +
add name attribute

2022-10-27 17:04 UTC, liliia-livandovskaya requested changes
GJ! Pay attention to the comments

2022-10-28 11:01 UTC, Anastasiia-Svintsova requested changes

2022-10-28 11:01 UTC, Anastasiia-Svintsova commented on src/index.html
> +    <form action="1" method="post">
Add a correct action to the form. As the task says: 
On form submit send form data to https://mate-academy-form-lesson.herokuapp.com/create-application

2022-10-28 14:35 UTC, Vitalii-Fediaiev commented on src/index.html
> +    <form action="1" method="post">
I don't understand!
do i have to create a server? or write any fictional one?

2022-10-31 11:05 UTC, Anastasiia-Svintsova requested changes
Please, fix a one little detail

2022-10-31 11:05 UTC, Anastasiia-Svintsova commented on src/index.html
> +    <form action="http://localhost:8080/api" method="post">
```suggestion
    <form 
      action="https://mate-academy-form-lesson.herokuapp.com/create-application"
      method="post"
     >
```

2022-10-31 18:02 UTC, Bohdan-Maksymiuk requested changes
Good job - fix your code style and fix test - smth went wrong 🙃 
pay attention to the top margin of first input in fieldset and bottom margin of the last input in fieldset

2022-10-31 18:02 UTC, Bohdan-Maksymiuk commented on src/index.html
> +          </textarea>
```suggestion
          <textarea
            required 
            name="feedback"
            minlength="1"
            maxlength="5"
        ></textarea>
```

2022-10-31 18:02 UTC, Bohdan-Maksymiuk commented on src/index.html
> +           Would you recommend us?
```suggestion
         Would you recommend us?
```

2022-12-22 08:54 UTC, closed without merging