Add HTML form
mate-academy/layout_html-form pull request #2610
Opened 2022-10-28 20:55 UTC by ruslanpashkov

https://ruslanpashkov.github.io/layout_html-form/
https://ruslanpashkov.github.io/layout_html-form/report/html_report/

2022-10-31 12:58 UTC, Ihor-Karpyn requested changes

2022-10-31 12:58 UTC, Ihor-Karpyn commented on src/index.html
> +            >
checlist p3, fix in all cases

2022-11-01 07:16 UTC, valerii-derkach approved these changes
find out how to prettify the demolinks

2022-11-01 07:16 UTC, valerii-derkach commented on src/index.html
> +        <div class="form-field">
these div containers are redundant here, you can just put classes directly to the label tags

you can simplify your code

2023-02-20 15:03 UTC, closed without merging