first commit - html and css built
mate-academy/layout_html-form pull request #2656
Opened 2022-11-01 10:41 UTC by Sergei-Nikolaienko

[DEMO LINK] https://Sergei-Nikolaienko.github.io/layout_html-form/
[TEST REPORT LINK] https://Sergei-Nikolaienko.github.io/layout_html-form/report/html_report/

2022-11-03 10:37 UTC, alexandra-protyanova requested changes

2022-11-03 10:37 UTC, alexandra-protyanova commented on src/style.css
> +  border: 1px solid black;
your tests are not passing because of this borders, use `legend` tag instead

2022-11-03 10:37 UTC, alexandra-protyanova commented on src/index.html
> +        <span class="headline">Personal information</span>
in this task divs and spans are absolutely redundant

2022-11-03 10:37 UTC, alexandra-protyanova commented on src/index.html
> +            No
```suggestion
              No
```

2022-11-03 10:37 UTC, alexandra-protyanova commented on src/style.css
> +  position: relative;
you only need margins and `display: block` in this task in styles

2022-11-04 18:49 UTC, SanyaBratashchuk requested changes

2022-11-04 18:49 UTC, SanyaBratashchuk commented on src/index.html
> +        </label>
```suggestion
        <label class="form__field" for="surname">
          Surname:
          <input 
            type="text" 
            id="surname" 
            autocomplete="off"
          >
        </label>
```

2022-11-04 18:49 UTC, SanyaBratashchuk commented on src/index.html
> +        <label class="form__field" for="name">Name:
```suggestion
        <label class="form__field" for="name">
          Name:
```

2022-11-04 18:49 UTC, SanyaBratashchuk commented on src/index.html
> +        <label class="form__field" for="name">Name:
Fix it everywhere

2022-11-04 18:49 UTC, SanyaBratashchuk commented on src/index.html
> +            No
Wrap each radio with label to make `yes` and `no` words clickable

2022-11-06 11:37 UTC, SanyaBratashchuk requested changes

2022-11-06 11:37 UTC, SanyaBratashchuk commented on src/index.html
> +              Yes
```suggestion
            <input 
              type="radio" 
              name="cats" 
              value="lovesCats"
            >
            Yes
```

2022-11-06 11:37 UTC, SanyaBratashchuk commented on src/index.html
> +              No
```suggestion
          <label>
            <input 
            type="radio" 
            name="cats" 
            value="hatesCats"
            >
            No
```

2022-11-06 11:37 UTC, SanyaBratashchuk commented on src/index.html
> +          <label class="cat-yes">
```suggestion
          <label>  
```

2022-11-06 11:37 UTC, SanyaBratashchuk commented on src/style.css
> +}
```suggestion
.form__field:last-child {
  margin-bottom: 0;
}
```

2022-11-07 10:29 UTC, DarkMistyRoom requested changes

2022-11-07 10:29 UTC, DarkMistyRoom commented on src/style.css
> +.form__field {
```suggestion
.form__field {
```

2022-11-07 10:29 UTC, DarkMistyRoom commented on src/index.html
> +            Do you love cats?
Move _Do you love cats?_ out the label because when you click on the question, yes becomes selected

2022-11-07 15:04 UTC, stanislav-topikha requested changes
remove spaces from textarea
![image](https://user-images.githubusercontent.com/99331793/200342767-d331ba31-8a7a-45a7-95cd-1fd468827d8e.png)

2022-11-07 17:33 UTC, Sergei-Nikolaienko commented
the only fix I've found for text area is by placing the closing tag on the same line as the opening one, however due to this the tests won't pass

2022-11-08 11:11 UTC, DarkMistyRoom approved these changes

2023-01-12 09:55 UTC, closed without merging