Develop
mate-academy/layout_html-form pull request #2680
Opened 2022-11-02 09:06 UTC by Sleptco

2022-11-03 12:36 UTC, alexandra-protyanova requested changes

2022-11-03 12:36 UTC, alexandra-protyanova commented on src/index.html
> +          >
```suggestion
          <input
            type="text"
            name="surname"
            autocomplete="off"
          >
```

2022-11-03 12:36 UTC, alexandra-protyanova commented on src/index.html
> +          >
read checklist and fix code style everywhere

2022-11-03 12:36 UTC, alexandra-protyanova commented on src/index.html
> +          Yes
yes and no should have separate label for them

2022-11-11 11:15 UTC, DarkMistyRoom requested changes
You should add links to the description https://www.loom.com/share/da672f3d083c4247960d02d43f7d527a

And your links don't work. Did you deploy the project?

2022-11-11 11:15 UTC, DarkMistyRoom commented on src/index.html
> +          >
```suggestion
          <input 
            type="text"
            name="name"
            autocomplete="off"
          >
```

2022-11-11 11:15 UTC, DarkMistyRoom commented on src/index.html
> +          >
each attribute on a new line

2022-11-11 11:15 UTC, DarkMistyRoom commented on src/index.html
> +        <label class="group">
Add empty lines between multiline sibling blocks of HTML

2022-11-11 11:15 UTC, DarkMistyRoom commented on src/index.html
> +        <label class="group">
Don't use this common label, because when you click on the question, yes becomes selected

2022-11-11 11:15 UTC, DarkMistyRoom commented on src/style.css
> +}
```suggestion
  margin-bottom: 0;
}
```

2022-11-11 17:10 UTC, Sleptco commented on src/index.html
> +        <label class="group">
![image](https://user-images.githubusercontent.com/116346992/201393059-187d3046-5790-4031-9f58-e73391acf22d.png)
  прибрав. не проходить тест. Як це виправити?

2022-11-25 14:02 UTC, DarkMistyRoom requested changes
Links still don't work. Did you deploy the project after the changes? Ask in the chat, if something goes wrong

2022-11-25 14:02 UTC, DarkMistyRoom commented on src/index.html
> +            >
```suggestion
              type="radio"
              name="cats"
              value="yes"
            >
```

2022-11-25 14:02 UTC, DarkMistyRoom commented on src/index.html
> +            >
fix it everywhere

2022-11-25 14:02 UTC, DarkMistyRoom commented on src/index.html
> +          <label>
```suggestion
          </label>
          
          <label>
```

2022-11-25 14:02 UTC, DarkMistyRoom commented on src/index.html
> +          <textarea></textarea>
Each field should have name attribute

2022-11-25 14:02 UTC, DarkMistyRoom commented on src/index.html
> +          <textarea></textarea>
and autocomplete off

2022-11-25 14:45 UTC, Sleptco commented
> * [DEMO LINK](https://Slepco.github.io/layout_html-form/)
> * [TEST REPORT LINK](https://Slepco.github.io/layout_html-form/report/html_report/)

2022-11-25 14:45 UTC, closed without merging