Develop
mate-academy/layout_html-form pull request #2753
Opened 2022-11-13 17:41 UTC by Viktor535x

2022-11-13 22:03 UTC, ivanchuk-yurii requested changes

2022-11-13 22:03 UTC, ivanchuk-yurii commented on src/index.html
> +          >
```suggestion
        <label class="lab_inp">
          Surname:
          <input
            type="text"
            id="fname"
            name="camelCase"
            required
          >
```
fix in other places

2022-11-13 22:03 UTC, ivanchuk-yurii commented on src/index.html
> +          <input type="Password" id="Password"
```suggestion
          <input type="password" id="Password"
```

2022-11-13 22:03 UTC, ivanchuk-yurii commented on src/index.html
> +        <li class="lab_inp">
don't use `li` without `ul/ol`

2022-11-13 22:03 UTC, ivanchuk-yurii commented on src/style.css
> +fieldset {
don't style tags

2022-11-13 22:03 UTC, ivanchuk-yurii commented on src/style.css
> +.lab_inp {
use full names for classes

2022-11-13 22:03 UTC, ivanchuk-yurii commented on src/index.html
> +      <fieldset enabled>
what is `enabled` for?

2022-11-14 08:28 UTC, closed without merging

2022-11-14 16:16 UTC, Bohdan-Maksymiuk reviewed
PR is closed - open it so we will able to check it