Develop
mate-academy/layout_html-form pull request #2788
Opened 2022-11-20 17:24 UTC by LeoSpartaDeV

https://leospartadev.github.io/layout_html-form/
https://leospartadev.github.io/layout_html-form/report/html_report/

2022-11-20 17:42 UTC, LeoSpartaDeV commented
https://leospartadev.github.io/layout_html-form/
https://leospartadev.github.io/layout_html-form/report/html_report/

2022-11-20 18:18 UTC, ivanchuk-yurii requested changes

2022-11-20 18:18 UTC, ivanchuk-yurii commented on src/index.html
> +          <label>
```suggestion
      <fieldset class="contacts__form-field">
        <legend>An interesting fact about you!</legend>
        <div class="contacts__form-item">Do you love cats?
          <label>
```

2022-11-20 18:18 UTC, ivanchuk-yurii commented on src/index.html
> +          </label>
```suggestion
            >
          </label>
```

2022-11-20 18:18 UTC, ivanchuk-yurii commented on src/index.html
> +          </textarea>
```suggestion
          ></textarea>
```
<img width="301" alt="image" src="https://user-images.githubusercontent.com/53611910/202918905-ebd02007-8394-4f35-94c3-476552e4cb56.png">

2022-11-20 18:18 UTC, ivanchuk-yurii commented on src/index.html
> +          </textarea>
to fix this

2022-12-25 13:17 UTC, LeoSpartaDeV commented on src/index.html
> +          </textarea>
> 

error  Tag’s closing bracket should be on  the same level as opening one   (closing-and-opening-on-seme-level)

2022-12-25 13:19 UTC, LeoSpartaDeV commented on src/index.html
> +          </textarea>
html lint error

2022-12-26 12:25 UTC, LeoSpartaDeV commented
+

2022-12-27 08:19 UTC, DarkMistyRoom commented on src/index.html
> +        </div>
Why don't you use a label here?

2022-12-27 08:19 UTC, DarkMistyRoom commented on src/index.html
> +        </div>
And here?

2022-12-27 08:19 UTC, DarkMistyRoom commented on src/index.html
> +          </textarea>
Yes, but it is just a linter cofig. If it is important for the element's behavior, you can skip it

2023-01-18 09:17 UTC, closed without merging