Povierienov HTML FORMe
mate-academy/layout_html-form pull request #2803
Opened 2022-11-22 22:02 UTC by vitpoverenov

Please check my FORM 
I need to pass the test
Have a good day!
Thanks for your attention!

2022-11-23 17:41 UTC, Viktor-Kost requested changes

2022-11-23 17:41 UTC, Viktor-Kost commented on src/index.html
> +           minvalue="0"
Check a syntax of min and max values [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/number)

2022-11-23 17:41 UTC, Viktor-Kost commented on src/index.html
> +          <input id="forname"
Please, read this checklist and apply recommendations for good styling for the WHOLE document
For example, here is a 3rd paragraph
[read](https://github.com/mate-academy/layout_html-form/blob/master/checklist.md)

2022-11-23 17:41 UTC, Viktor-Kost commented on src/index.html
> +        <label for="formdate">
Use one case for naming classes, cause you have used at least three types instead of one
Check the WHOLE document

[read](https://betterprogramming.pub/string-case-styles-camel-pascal-snake-and-kebab-case-981407998841)

2022-11-23 17:41 UTC, Viktor-Kost commented on src/style.css
> +label {
Use class selectors instead of tag one

2022-11-23 17:41 UTC, Viktor-Kost commented on src/style.css
> +
Extra empty line

```suggestion

```

2022-11-23 17:41 UTC, Viktor-Kost commented on src/style.css
> +button {
Use style selectors instead of tag ones

2022-11-23 17:41 UTC, Viktor-Kost commented on src/style.css
> +.label1 {
You can apply one class for the same blocks

So you will have only one class `.label` for labels
And one class `.fieldset `for fieldsets

2022-11-23 18:02 UTC, vitpoverenov commented on src/index.html
> +           minvalue="0"
> Check a syntax of min and max values [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/number)

Ok!

2022-11-23 18:24 UTC, vitpoverenov commented on src/style.css
> +.label1 {
Ok
I fixed it and than deployed again! 
Thanks

2022-11-24 08:25 UTC, stanislav-topikha requested changes
recheck and fix previous comments ⬆️ 

Don't forget to add demo and test report link

https://user-images.githubusercontent.com/99331793/203729891-f2707f20-59af-4850-8f23-85acf62f7eb8.mov

you dont need 90% of your styles, it should be like this 
20ish rows, not more
<img width="372" alt="image" src="https://user-images.githubusercontent.com/99331793/203730432-7d4bd5a6-494b-4437-b18a-8c62a2a486e3.png">

2022-11-24 22:11 UTC, vitpoverenov commented on src/index.html
> +          <input id="forname"
Viktor ! Спасибо огромное что помогаете и смотрите код! 
Я очень стараюсь все исправить!
Спасибо за внимание!
Сделаю - залью!
Код изменил в ЦСС с 80 строк до 25 как и писали.

2022-11-25 17:40 UTC, SanyaBratashchuk requested changes
Can't see changes since previous review. Maybe you forgot to push your changes

2022-11-27 14:52 UTC, SanyaBratashchuk requested changes
Check your code style with [checklist](https://github.com/mate-academy/layout_html-form/blob/master/checklist.md)

2022-11-27 14:52 UTC, SanyaBratashchuk commented on src/style.css
> +}
![image](https://user-images.githubusercontent.com/97547824/204141642-81e981b7-7bad-46b3-b128-de40c0846e52.png)

2022-11-28 12:55 UTC, vitpoverenov commented
> Can't see changes since previous review. Maybe you forgot to push your changes

I did 
check plz
dont understand what a problem now

2022-11-28 12:55 UTC, vitpoverenov commented
1

2022-11-28 16:28 UTC, vitpoverenov commented
> Please check my FORM I need to pass the test Have a good day! Thanks for your attention!
> 
> * [DEMO LINK](https://vitpoverenov.github.io/layout_html-form/)
> * [TEST REPORT LINK](https://vitpoverenov.github.io/layout_html-form/report/html_report/)

Черным по белому же написано было - добавить в описание к пр. 
Буду внимательней, спасибо!

Что еще исправить ? Все сделал вроде.

2022-11-29 18:16 UTC, AlisaVlasova requested changes

2022-11-29 18:16 UTC, AlisaVlasova commented on src/index.html
> +     method="post">
```suggestion
    <form
      class="form"
      action="https://mate-academy-form-lesson.herokuapp.com/create-application"
      method="post"
    >
```
onsubmit="onSubmit(Submit)" тут не потрібен, давай ще розставимо гарненько атрибути в тегах, згідно з чеклістом, ось приклад

2022-11-29 18:16 UTC, AlisaVlasova commented on src/index.html
> +          >
```suggestion
          <input class="form-number"
            type="number"
            id="number"
            value="12"
            min="0"
            max="100"
          >
```
відступ від артибута до відкриваючої і закриваючої скобки має бути не один пробіл, а один тег

2022-11-29 18:16 UTC, AlisaVlasova commented on src/index.html
> +          >
```suggestion
          <input
            id="formdate"
            type="date"
            name="formdate"
          >
          або кожен атрибут з нового рядка, або все в одному (якщо не більше трьох)
                    <input id="formdate" type="date" name="formdate">
```

2022-11-29 18:16 UTC, AlisaVlasova commented on src/index.html
> +          No
```suggestion
          <input
            type="radio"
            name="сats"
          >
          Yes
          <input
            type="radio"
            name="сats"
          >
          No
```
радіо інпути мають мати однакове name інакше вони не зв'язані і можна обрати обидва варіанти одночасно

2022-11-29 18:16 UTC, AlisaVlasova commented on src/index.html
> +       value="Submit">
value зайве

2022-11-29 18:17 UTC, AlisaVlasova commented on src/index.html
> +          >
*один tab)

2022-12-14 20:07 UTC, closed without merging