solution
mate-academy/layout_html-form pull request #2847
Opened 2022-12-01 12:03 UTC by yarik-bachynskyi

2022-12-01 19:21 UTC, SanyaBratashchuk requested changes

2022-12-01 19:21 UTC, SanyaBratashchuk commented on src/index.html
> +        <div>
Why do you need this `div`s?

2022-12-01 19:21 UTC, SanyaBratashchuk commented on src/style.css
> +}
```suggestion
```

2022-12-01 19:21 UTC, SanyaBratashchuk commented on src/index.html
> +      <fieldset>
```suggestion
      <fieldset class="field-blocks">
```

2022-12-29 18:07 UTC, loralevitska requested changes
Please deploy your solution, and before review check demo_link
![image](https://user-images.githubusercontent.com/70009205/209992182-781f9010-a8e7-4aff-bccf-3a97c8dd38e8.png)
Pay attention to comments

2022-12-29 18:07 UTC, loralevitska commented on src/index.html
> +        <div>
not fixed. remove redundant `div`s. If you have any questions, please ask them in fe_chat and tag mentors. It will be faster, because your answers in GitHub will be visible to mentor only after you re-request review

2023-01-10 00:02 UTC, closed without merging