New Commit for mentors fix all request
mate-academy/layout_html-form pull request #2941
Opened 2022-12-14 21:54 UTC by vitpoverenov

- [DEMO LINK]  ( https://vitpoverenov.github.io/layout_html-form/ )
- [TEST REPORT LINK]  ( https://vitpoverenov.github.io/layout_html-form/report/html_report/ )

2022-12-14 21:54 UTC, vitpoverenov commented
- [DEMO LINK](https://vitpoverenov.github.io/layout_html-form/)
- [TEST REPORT LINK](https://vitpoverenov.github.io/layout_html-form/report/html_report/)

2022-12-15 18:33 UTC, SanyaBratashchuk requested changes

2022-12-15 18:33 UTC, SanyaBratashchuk commented on src/index.html
> +          </textarea>
```suggestion
          <textarea id="textarea" name="Comments"
          cols="20" rows="2"
          ></textarea>
```
To avoid it 
![image](https://user-images.githubusercontent.com/97547824/207939821-c69b38dc-1014-4e4c-96d8-e8934a385d5c.png)

2022-12-15 18:33 UTC, SanyaBratashchuk commented on src/index.html
> +        </label>
Wrap each radio with label to make `yes` and `no` words clickable

2022-12-15 18:33 UTC, SanyaBratashchuk commented on src/style.css
> +}
![image](https://user-images.githubusercontent.com/97547824/207940015-574416c6-aedc-4860-8198-69d9415c5fa0.png)

2022-12-16 22:49 UTC, vitpoverenov commented on src/index.html
> +          </textarea>
I fixed it
Check plz

2022-12-17 08:54 UTC, SanyaBratashchuk requested changes

2022-12-17 08:54 UTC, SanyaBratashchuk commented on src/style.css
> +}
Why do you need two identical classes?

2022-12-17 08:54 UTC, SanyaBratashchuk commented on src/style.css
> +}
```suggestion
.label:not(:last-child) {
  margin-bottom: 10px;
}
```

2022-12-19 12:19 UTC, vitpoverenov commented on src/style.css
> +}
I fixed it!

2022-12-19 17:00 UTC, ViktorHavryliuk commented on src/index.html
> +            > Yes
Tag text should be on new line

2022-12-19 17:03 UTC, ViktorHavryliuk commented on src/index.html
> +        <label class="label" for="recommend" > Would you recommend us?
"Would you recommend us?" should be on a new line

2022-12-19 17:03 UTC, ViktorHavryliuk commented on src/index.html
> +        >
Fix identation here as well

2023-01-05 22:22 UTC, closed without merging