Develop
mate-academy/layout_html-form pull request #3012
Opened 2022-12-27 18:46 UTC by AndriiTorhashov

2022-12-28 13:49 UTC, Viktor-Kost requested changes

2022-12-28 13:49 UTC, Viktor-Kost commented on src/index.html
> +      >
```suggestion
    <form 
      action="https://mate-academy-form-lesson.herokuapp.com/create-application" 
      method="post"
      class="form"
    >
```

2022-12-28 13:49 UTC, Viktor-Kost commented on src/index.html
> +        </div>
Please check code styling moments ALL OVER the page. Especially point 2-3
[Recommendations](https://github.com/mate-academy/layout_html-form/blob/master/checklist.md)
```suggestion
      <fieldset class="group">
        <legend>Personal information</legend>
        <div class="simple">
          <label>
            Surname:
            <input 
              type="text" 
              name="sname" 
              required 
              autocomplete="off"
            >
          </label> 
        </div>
```

2022-12-28 13:49 UTC, Viktor-Kost commented on src/index.html
> +        <div class="line"></div>
No needs to add an html element to make a styling issue. 
Use css

2022-12-28 13:49 UTC, Viktor-Kost commented on src/index.html
> +        </div>
it is a redundant `div` wrapper. You can add styles to `label`. Remove `div` at other similar places as well

2022-12-28 13:49 UTC, Viktor-Kost commented on src/index.html
> +          </label>
Here you need two labels. 
labels should wrap ONLY inputs. 
Do you love cats? should not be wrapped into a label

2022-12-28 13:49 UTC, Viktor-Kost commented on src/index.html
> +      <fieldset class="group">
is too big distance between siblings
```suggestion
      </fieldset>

      <fieldset class="group">
```

2022-12-28 13:49 UTC, Viktor-Kost commented on src/index.html
> +      <fieldset class="group">
is too big distance between siblings. Check all over the page
```suggestion
      </fieldset>

      <fieldset class="group">
```

2022-12-28 13:49 UTC, Viktor-Kost commented on src/index.html
> +
delete these empty lines

2022-12-28 13:49 UTC, Viktor-Kost commented on src/style.css
> +}/* styles go here */
delete unused comments

2022-12-28 13:49 UTC, Viktor-Kost commented on src/style.css
>  /* styles go here */
delete unused comments

2022-12-28 13:49 UTC, Viktor-Kost commented on src/style.css
> +
extra empty line

2022-12-28 13:49 UTC, Viktor-Kost commented on src/style.css
> +}
``
```suggestion
```

2022-12-28 13:49 UTC, Viktor-Kost commented on src/style.css
> +}
``
```suggestion
```

2022-12-28 13:49 UTC, Viktor-Kost commented on src/index.html
> +          id="sb"
why do you need this id?

2022-12-30 15:08 UTC, Viktor-Kost commented on src/index.html
> +      >
is not fixed

2022-12-30 15:08 UTC, Viktor-Kost commented on src/index.html
> +        </div>
is not fixed

2022-12-30 15:08 UTC, Viktor-Kost commented on src/index.html
> +        <div class="line"></div>
is not fixed

2022-12-30 15:10 UTC, Viktor-Kost requested changes
Pay attention to unresolved conversations. 
I guess you haven't committed changes

If you need any help - ask at fe_chat

2022-12-30 15:13 UTC, AndriiTorhashov commented
Я перезалив вже завдання, де всі помилки виправив. Це завдання тести
пройшло. Можливо я якось не правильно його відправив на гіт хаб, але наче
все завантажилось.
пт, 30 груд. 2022 р. о 17:10 Viktor-Kost ***@***.***> пише:

> ***@***.**** requested changes on this pull request.
>
> Pay attention to unresolved conversations.
> I guess you haven't committed changes
>
> If you need any help - ask at fe_chat
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mate-academy/layout_html-form/pull/3012#pullrequestreview-1233133968>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4TKHJKO6DSKYP3C5FITMQ3WP33N5ANCNFSM6AAAAAATKUPHFI>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2023-01-19 21:04 UTC, closed without merging