Develop
mate-academy/layout_html-form pull request #3014
Opened 2022-12-27 23:02 UTC by Dimoshua

Request description:
- [DEMO LINK](https://Dimoshua.github.io/layout_html-form/)
- [TEST REPORT LINK](https://Dimoshua.github.io/layout_html-form/report/html_report/)

2022-12-28 19:47 UTC, SanyaBratashchuk requested changes

2022-12-28 19:47 UTC, SanyaBratashchuk commented on src/index.html
> +        <label for="surname" class="block">Surname:
```suggestion
        <label for="surname" class="block">
          Surname:
```

2022-12-28 19:47 UTC, SanyaBratashchuk commented on src/index.html
> +        <label for="name" class="block">Name:
```suggestion
        <label for="name" class="block">
          Name:
```
Fix it everywhere

2022-12-28 19:47 UTC, SanyaBratashchuk commented on src/index.html
> +        <label class="block">Do you love cats?
It shouldn't be a label because when I click on the question `yes` become selected

2022-12-28 19:47 UTC, SanyaBratashchuk commented on src/style.css
> +.block {
add this class for each fieldWrapper and use `:last-child` pseudoclass

2022-12-29 08:22 UTC, Dimoshua commented on src/index.html
> +        <label for="surname" class="block">Surname:
It's done

2022-12-29 08:22 UTC, Dimoshua commented on src/index.html
> +        <label for="name" class="block">Name:
It's done

2022-12-29 08:22 UTC, Dimoshua commented on src/index.html
> +        <label class="block">Do you love cats?
It's done

2022-12-29 08:52 UTC, Dimoshua commented on src/style.css
> +.block {
It's done

2022-12-29 08:52 UTC, closed without merging