complete task
mate-academy/layout_html-form pull request #31
Opened 2023-01-09 21:24 UTC by VladGraund

- [DEMO LINK](https://VladGraund.github.io/layout_html-form/)
- [TEST REPORT LINK](https://VladGraund.github.io/layout_html-form/report/html_report/)

2023-01-10 15:39 UTC, mykhalenych requested changes

2023-01-10 15:39 UTC, mykhalenych commented on src/index.html
> +            <label for="name">Name:
`<label for="name">Name:</label>`

2023-01-10 15:39 UTC, mykhalenych commented on src/index.html
> +            <label for="date">Full date of birth:
change all labels

2023-01-11 15:32 UTC, mykhalenych requested changes

2023-01-11 15:32 UTC, mykhalenych commented on src/index.html
> +            <label for="name">Name:
didn't fix it, when you wrap the inputs you don't need for, use for without wrap inputs, or delete for and add spaces
```
<label for="name">
   Name:
   <input
```

2023-01-12 12:24 UTC, IvanFesenko requested changes
Some fix require

2023-01-12 12:24 UTC, IvanFesenko commented on src/index.html
> +          </label>
Do not use block element like div inside inline elements
```suggestion
          <div  class="container">
            <label>
              What is your favorite color?
              <input
                type="color"
                name="col"
                id="col"
              >
            </label>
          </div>
```

2023-01-12 12:24 UTC, IvanFesenko commented on src/index.html
> +            <div class="container">
Same here

2023-01-12 15:07 UTC, mykhalenych approved these changes

2025-02-28 14:00 UTC, closed without merging