done
mate-academy/layout_html-form pull request #365
Opened 2023-02-21 00:43 UTC by VladyslavKucher

- [DEMO LINK](https://VladyslavKucher.github.io/layout_html-form/)
- [TEST REPORT LINK](https://VladyslavKucher.github.io/layout_html-form/report/html_report/)

2023-02-21 07:30 UTC, qoa11a requested changes
please, provide working test report link

2023-02-21 22:42 UTC, VladyslavKucher commented
https://VladyslavKucher.github.io/layout_html-form/report/html_report/
This is a corect test report link. However, it is not working. It would be highly appreciated, if you could tell me how can I fix it:)
If this test created to check html linter, below you will se attached screenshot of "npm run lint"
![image](https://user-images.githubusercontent.com/125765489/220475428-0f6d7639-7c4e-42a5-8cb7-4bf60d7c3129.png)

2023-02-23 01:53 UTC, VladyslavKucher commented
file:///C:/Users/MyHome/Desktop/projects/projectLayoutHtmlForm/layout_html-form/backstop_data/html_report/index.html

2023-02-23 08:11 UTC, polosanya requested changes
![image](https://user-images.githubusercontent.com/96409563/220852509-e9d9fce7-0a5b-42d9-a028-8f675d8918fd.png)
Test link is still not working.
If you have any questions, please ask them in fe_chat and tag mentors. It will be faster because your answers in GitHub will be visible to the mentor only after you re-request review 🙂

2023-02-23 08:11 UTC, polosanya commented on src/index.html
> +          >
```suggestion
          <input 
            type="text" 
            name="attribute" 
            autocomplete="off" 
            required
          >
```
Fix all cases
![image](https://user-images.githubusercontent.com/96409563/220852632-7fe0848c-320d-49e8-9b0b-3865bb0a42b7.png)

2023-02-23 08:11 UTC, polosanya commented on src/index.html
> +        </div>
![image](https://user-images.githubusercontent.com/96409563/220852708-07b1bba1-61d4-46cc-84ad-ab25806e4adf.png)

2023-02-23 23:39 UTC, closed without merging