layout_html-form
mate-academy/layout_html-form pull request #403
Opened 2023-02-25 14:22 UTC by AnastasiiaSemenovaa

- [DEMO LINK](https://AnastasiiaSemenovaa.github.io/layout_html-form/)
- [TEST REPORT LINK](https://AnastasiiaSemenovaa.github.io/layout_html-form/report/html_report/)

2023-02-25 14:39 UTC, Volodymyr-Melnyk-Fron10der requested changes
Cool, just a few syntax issues I see

2023-02-25 14:39 UTC, Volodymyr-Melnyk-Fron10der commented on src/index.html
> +          >
```suggestion
          <input 
            type="text" 
            name="surname"
            autocomplete="off" 
          >
```

2023-02-25 14:39 UTC, Volodymyr-Melnyk-Fron10der commented on src/index.html
> +          >
check it throughout your code

2023-02-25 14:39 UTC, Volodymyr-Melnyk-Fron10der commented on src/index.html
> +        <label class="label">
add one empty line between large siblings to make code more readable

2023-02-25 14:39 UTC, Volodymyr-Melnyk-Fron10der commented on src/index.html
> +        <label class="label">
```suggestion
        </label>
        
        <label class="label">
          What is your favorite color? <input type="color" name="color" >
        </label>
        
        <label class="label">
          What time do you go to bed? <input type="time" name="bedTime" >
        </label>
        
        <label class="label">
```

2023-02-25 15:03 UTC, Volodymyr-Melnyk-Fron10der requested changes

2023-02-25 15:03 UTC, Volodymyr-Melnyk-Fron10der commented on src/index.html
> +          >
```suggestion
          <input 
            type="date" 
            name="birthday" 
          >
```

2023-02-25 15:03 UTC, Volodymyr-Melnyk-Fron10der commented on src/index.html
> +      <fieldset class="fieldset">
```suggestion
        </label>
      </fieldset>
      
      <fieldset class="fieldset">
```

2023-02-25 15:03 UTC, Volodymyr-Melnyk-Fron10der commented on src/index.html
> +          >
```suggestion
          <input type="checkbox" name="acceptTerm">
```

2023-02-25 15:03 UTC, Volodymyr-Melnyk-Fron10der commented on src/index.html
> +      <fieldset class="fieldset">
```suggestion
        </label>
      </fieldset>
      
      <fieldset class="fieldset">
```

2023-02-25 15:03 UTC, Volodymyr-Melnyk-Fron10der commented on src/index.html
> +          <label>
no space between parent and child
```suggestion
        <label class="label">
          <label>
```

2023-02-25 15:03 UTC, Volodymyr-Melnyk-Fron10der commented on src/index.html
> +        <label class="label">
```suggestion
          </label>
        </label>
        
        <label class="label">
```

2023-02-25 15:03 UTC, Volodymyr-Melnyk-Fron10der commented on src/index.html
> +      <fieldset class="fieldset">
```suggestion
        </label>
      </fieldset>
      
      <fieldset class="fieldset">
```

2023-02-25 15:03 UTC, Volodymyr-Melnyk-Fron10der commented on src/index.html
> +      </fieldset>
```suggestion
        </label>
      </fieldset>
```

2023-02-25 15:23 UTC, Volodymyr-Melnyk-Fron10der approved these changes
Nice job👍

2023-02-27 11:55 UTC, DarkMistyRoom approved these changes

2023-03-09 19:55 UTC, SanyaBratashchuk approved these changes

2023-03-10 12:25 UTC, closed without merging