Add html form
mate-academy/layout_html-form pull request #435
Opened 2023-03-02 19:41 UTC by SuprunArtem

2023-03-02 19:44 UTC, SuprunArtem commented
Add html form

2023-03-03 08:54 UTC, DarkMistyRoom requested changes
Add links to description. and push the readme file

2023-03-03 08:54 UTC, DarkMistyRoom commented on src/index.html
> +      <fieldset class="fieldset">
```suggestion
    <form action="https://mate-academy-form-lesson.herokuapp.com/create-application" method="post">
      <fieldset class="fieldset">
```

2023-03-03 08:54 UTC, DarkMistyRoom commented on src/index.html
> +      <fieldset class="fieldset">
Don't add an empty line between parent and child

2023-03-03 08:54 UTC, DarkMistyRoom commented on src/index.html
> +          type="text"
```suggestion
          <input 
            type="text"
```

2023-03-03 08:54 UTC, DarkMistyRoom commented on src/index.html
> +          <label>
Don't use this common label, because when you click on the question, yes becomes selected

2023-03-03 08:54 UTC, DarkMistyRoom commented on src/index.html
> +            </option>
```suggestion
            <option value="Bmw">
              Bmw
            </option>
```

2023-03-03 08:54 UTC, DarkMistyRoom commented on src/index.html
> +          <input
```suggestion
        <label class="form-field">
          How do you rate our work?
          <input
```

2023-03-03 08:54 UTC, DarkMistyRoom commented on src/index.html
> +          <input
fix it everywhere

2023-03-03 08:54 UTC, DarkMistyRoom commented on src/index.html
> +            </textarea>
![image](https://user-images.githubusercontent.com/98764641/222675887-85ecd7c0-a452-438b-9156-90bbc9339d62.png)

2023-03-03 08:54 UTC, DarkMistyRoom commented on src/index.html
> +</html>
add the empty line

2023-03-05 10:12 UTC, SanyaBratashchuk requested changes

2023-03-05 10:12 UTC, SanyaBratashchuk commented on src/index.html
> +
```suggestion
```

2023-03-05 10:12 UTC, SanyaBratashchuk commented on src/index.html
> +            <select    name="recommended">
```suggestion
            <select name="recommended">
```

2023-03-05 10:12 UTC, SanyaBratashchuk commented on src/index.html
> +</html>
```suggestion
</html>

```

2023-03-08 13:45 UTC, anstsot requested changes
Please check the demo link and report links. they are not working
and please fix all comments above

2023-03-08 19:26 UTC, polosanya requested changes
Your links still don't work properly. Feel free to ask for help in the chat if you have any difficulties

2023-03-08 22:29 UTC, closed without merging