Lesson 2, Task 1 'HTML Form' - Done!
mate-academy/layout_html-form pull request #451
Opened 2020-08-26 10:50 UTC by Atteroot

- [DEMO LINK](https://Atteroot.github.io/layout_html-form/)
- [TEST REPORT LINK](https://Atteroot.github.io/layout_html-form/report/html_report/)

2020-08-26 14:57 UTC, solaryasha requested changes

2020-08-26 14:57 UTC, solaryasha commented on src/index.html
> +          <span>Would you recommend us?</span>
Давай краще обгорнемо `select` лейблом.

2020-08-26 14:57 UTC, solaryasha commented on src/index.html
> +    </button>
```suggestion
    <button
      id ="button"
      type="submit"
      onsubmit="onSubmit()"
    >
      Submit
    </button>
```

2020-08-27 08:09 UTC, Atteroot commented on src/index.html
> +          <span>Would you recommend us?</span>
Done!

2020-08-27 08:09 UTC, Atteroot commented on src/index.html
> +    </button>
Fixed!

2020-08-27 08:14 UTC, solaryasha approved these changes
🚀

2021-03-23 18:57 UTC, closed without merging