Develop
mate-academy/layout_html-form pull request #471
Opened 2023-03-06 17:08 UTC by kq333

task with forms done

2023-03-07 08:00 UTC, michalcywka requested changes
I marked some of the mistakes,  please have a careful look at the checklist. Also please do not commit ```package-lock.json``` file.

2023-03-07 08:00 UTC, michalcywka commented on .eslintrc.js
>  module.exports = {
Don't change this file please :)

2023-03-07 08:00 UTC, michalcywka commented on .linthtmlrc.json
> -  "extends": "@mate-academy/linthtml-config"
Don't change this file please :)

2023-03-07 08:00 UTC, michalcywka commented on src/index.html
> +              placeholder="dd / mm / yyyy"
Too much indentation

2023-03-07 08:00 UTC, michalcywka commented on src/index.html
> +        >
Please have a look at notes in readme.md

2023-03-07 08:00 UTC, michalcywka commented on src/style.css
> +fieldset {
Checklist point 6

2023-03-07 09:57 UTC, kq333 commented on .linthtmlrc.json
> -  "extends": "@mate-academy/linthtml-config"
I have not changed this file.

2023-03-07 13:06 UTC, michalcywka requested changes
Two links with GitHub Pages that are required in the description are missing.

2023-03-07 13:06 UTC, michalcywka commented on src/index.html
> +    <form action="http://localhost:3000/api" method="post">
Action should be something else (readme.md)

2023-03-07 15:15 UTC, michalcywka requested changes
Please read carefully point 19 from [tutorial](https://mate-academy.github.io/layout_task-guideline/#how-to-solve-the-layout-tasks-on-github) Links in the description are missing.

2023-03-08 07:59 UTC, michalcywka requested changes
Please look at Pull Requests from other people and see how their description looks like. The links from description here in the PR are still missing.

2023-03-08 07:59 UTC, michalcywka commented on src/index.html
> +        ></textarea>
Please have a closer look at the readme.md file on how to fix this issue

2023-03-08 07:59 UTC, michalcywka commented on src/style.css
> +.fieldset > div:not(:last-of-type) {
Checklist point 6
It would be better to use another class (similar to 'comments-rec') and use it in divs around inputs and labels.

2023-03-08 09:55 UTC, michalcywka requested changes
Please see my message on Slack.

2023-03-08 10:01 UTC, kq333 commented
[DEMO LINK](https://kq333.github.io/layout_html-form/)
[TEST REPORT LINK](https://kq333.github.io/layout_html-form/report/html_report/)

2023-03-08 10:12 UTC, michalcywka requested changes

2023-03-08 10:12 UTC, michalcywka commented on src/index.html
> +        ></textarea>
This needs to be fixed :) Look at Tips&Hints in readme.md, point 4

2023-03-08 10:12 UTC, michalcywka commented on src/index.html
> +              type="date"
Checklist point 3

2023-03-08 10:12 UTC, michalcywka commented on .linthtmlrc.json
> -  "extends": "@mate-academy/linthtml-config"
I understand, this is a side effect of `npm install`. Nevertheless you should only commit files that you have changed yourself. One way to fix this is to copy the original content of the file and commit it again :)

2023-03-08 12:23 UTC, michalcywka requested changes

2023-03-08 12:23 UTC, michalcywka commented on src/index.html
> +    <form action="https://mate-academy-form-lesson.herokuapp.com/create-application" method="POST"
Checklist point 1 (make it look like checklist point 3)

2023-03-08 12:23 UTC, michalcywka commented on src/index.html
> +              step="2"
Checklist point 3

2023-03-08 12:23 UTC, michalcywka commented on src/index.html
> +          name="coments"
checklist point 3

2023-03-08 12:56 UTC, michalcywka requested changes

2023-03-08 12:56 UTC, michalcywka commented on src/index.html
> +    <button type="submit">Submit</button>
Button should be in form, don't use <br> tags to make space :)

2023-03-08 12:56 UTC, michalcywka commented on src/index.html
> +          <textarea
Please fix linter error here.

2023-03-08 12:56 UTC, michalcywka commented on src/index.html
> +      action="https://mate-academy-form-lesson.herokuapp.com/create-application" method="POST"
If you do it like this, attributes need to follow checklist point 3 also

2023-03-09 07:58 UTC, michalcywka requested changes

2023-03-09 07:58 UTC, michalcywka commented on src/index.html
> +            multiple>
Checklist point 3

2023-03-09 07:58 UTC, michalcywka commented on src/index.html
> +          ></textarea>
There is still a problem here.

2023-03-09 09:20 UTC, michalcywka requested changes
Still needs textarea fix

2023-03-09 10:48 UTC, michalcywka requested changes
Still not all the necessary files are reverted

2023-03-09 13:12 UTC, michalcywka requested changes
Unnecessary files are still present in the Pull Request.

2023-03-09 13:14 UTC, michalcywka approved these changes

2023-10-03 20:22 UTC, closed without merging