solution
mate-academy/layout_html-form pull request #485
Opened 2020-08-27 09:16 UTC by Pavliklaw7

- [DEMO LINK](https://Pavliklaw7.github.io/layout_html-form/) <br>
- [TEST REPORT LINK](https://Pavliklaw7.github.io/layout_html-form/report/html_report/)

2020-08-27 09:26 UTC, Vladimir-Beliy reviewed
не используй camelCase в html

2020-08-27 09:26 UTC, Vladimir-Beliy commented on src/index.html
> +        <label for="radioButtonNo">Yes</label>
```suggestion
        <label for="radioButtonNo">
          Yes
          <input
            type="radio"
            name="radioButton"
            id="radioButtonNo" 
            value="yes"
          >
        </label>
```
отредактируй все в соотвествии с этим примером

2020-08-27 10:30 UTC, Vladimir-Beliy commented
ты пропустил комментарий https://github.com/mate-academy/layout_html-form/pull/485#discussion_r478281318

2020-08-28 08:57 UTC, danheim requested changes

2020-08-28 08:57 UTC, danheim commented on src/index.html
> +          >
fix an indentation everywhere
```suggestion
          <input
            type="number"
            id="age"
            name="age"
            value="12"
            required
            min="0"
            max="100"
          >
```

2020-08-28 08:57 UTC, danheim commented on src/style.css
> +}
Style classes, not tags

2020-08-28 10:34 UTC, danheim approved these changes

2020-10-18 09:16 UTC, closed without merging