work with form
mate-academy/layout_html-form pull request #503
Opened 2023-03-09 18:47 UTC by RuslanKhoroshylov

2023-03-10 08:22 UTC, vlad-demchuk requested changes
add links to PR description

2023-03-10 08:22 UTC, vlad-demchuk commented on src/index.html
> +          <input type="text" autocomplete="off">
```suggestion
        <label class="field">
          Surname:
          <input type="text" autocomplete="off">
```

2023-03-10 08:22 UTC, vlad-demchuk commented on src/index.html
> +          <input type="text" autocomplete="off">
```suggestion
          Name:
          <input type="text" autocomplete="off">
```
no need to add these indents, fix all cases

2023-03-10 08:22 UTC, vlad-demchuk commented on src/index.html
> +          >
check your code style
<img width="912" alt="image" src="https://user-images.githubusercontent.com/102411130/224261722-817a90d8-e404-4e32-b9c5-3d50db2d065e.png">

2023-03-10 08:22 UTC, vlad-demchuk commented on src/index.html
> +          >
fix all such cases

2023-03-10 11:42 UTC, RuslanKhoroshylov commented on src/index.html
> +          >
all changes complete

2023-03-11 08:17 UTC, etojeDenys approved these changes
looks good, but add DEMO, Report link

2023-03-11 08:18 UTC, etojeDenys requested changes
:)

2023-03-12 15:30 UTC, RuslanKhoroshylov commented
не пойму что за DEMO и где ее взять

2023-03-14 17:19 UTC, closed without merging