commit
mate-academy/layout_html-form pull request #548
Opened 2023-03-16 16:17 UTC by bohdanmayor

2023-03-16 16:29 UTC, Viktor-Kost requested changes
Hello!)

Please add a DEMO link to a Pull Request description

2023-03-16 16:29 UTC, Viktor-Kost commented on src/style.css
> +}
use class selectors instead of tag ones

2023-03-16 16:29 UTC, Viktor-Kost commented on src/index.html
> +        <div class="personalInformation">
no needs to use this wrapper `<div class="personalInformation">`

2023-03-16 16:29 UTC, Viktor-Kost commented on src/index.html
> +          </div>
you can remove `<div class="personalInformationField">` wrapper. It's redundant. And refactor each of your input/label connection like this:

```suggestion
            <label class="field">
              Surname:
              <input 
                type="text" 
                name="surname" 
              >
            </label>
```

Apply all over the page

2023-03-16 16:29 UTC, Viktor-Kost commented on src/index.html
> +            <input type="text" name="name" id="name">
Text fields should have autocomplete="off"

2023-03-16 16:29 UTC, Viktor-Kost commented on src/index.html
> +            <input type="number" id="old" name="old" value="12" min="1" max="100">
if it has several attributes, you need to put each of them on its own line.

2023-03-16 20:06 UTC, bohdanmayor commented
hello, idk, but demo link and test report link dont working, so I didn't got appruve from first project with auto tests (hello-world...)

2023-03-17 07:52 UTC, etojeDenys requested changes
you can ask about how to deploy the project and add links to PR in the slack chat

2023-03-17 07:52 UTC, etojeDenys commented on src/style.css
> +}
move to html selector

2023-03-17 08:17 UTC, etojeDenys requested changes
add links to your PR or feel free to ask about that in the slack chat

2023-03-17 08:26 UTC, bohdanmayor commented
> add links to your PR or feel free to ask about that in the slack chat

what it is PR?

2023-03-17 10:25 UTC, DarkMistyRoom requested changes
there should be required fields

2023-03-17 10:25 UTC, DarkMistyRoom commented on readme.md
> +- [TEST REPORT LINK](https://bohdanmayor.github.io/layout_html-form/report/html_report/)
add TEST REPORT LINK to the description too

2023-03-17 10:25 UTC, DarkMistyRoom commented on src/style.css
> +}
Remember, any other styles besides margins, should be browser default.

2023-03-17 10:25 UTC, DarkMistyRoom commented on src/style.css
> +}
![image](https://user-images.githubusercontent.com/98764641/225877659-7d554c92-5c6e-4e3e-9fd9-1ae09943d502.png)

2023-03-17 10:25 UTC, DarkMistyRoom commented on src/index.html
> +        </div>
use label for this element too

2023-03-17 10:25 UTC, DarkMistyRoom commented on src/index.html
> +        </div>
you should use it for all fields. check it everwhere

2023-03-17 10:25 UTC, DarkMistyRoom commented on src/index.html
> +    >
```suggestion
    <form 
      class="registerForm"
      action="https://mate-academy-form-lesson.herokuapp.com/create-application"
      method="post"
    >
```

2023-03-17 10:25 UTC, DarkMistyRoom commented on src/index.html
> +    >
keep the code style

2023-03-17 10:25 UTC, DarkMistyRoom commented on src/index.html
> +    >
fix it everywhere

2023-03-17 10:25 UTC, DarkMistyRoom commented on src/index.html
> +        <div>
Add empty lines between multiline sibling blocks of HTML

2023-03-17 10:25 UTC, DarkMistyRoom commented on src/style.css
> +  margin: 20px 0;
use one-direction margin. only margin-top or margin-bottom

2023-03-17 13:59 UTC, IvanFesenko requested changes
It should be multi select. Also check my comments
![Uploading 2023-03-17_15h58_53.png…]()

2023-03-17 13:59 UTC, IvanFesenko commented on src/index.html
> +            >
Pay attention on indents
```suggestion
            <input
              type="radio"
              id="yes"
              name="love-cats"
              value="yes"
            >
```

2023-03-17 13:59 UTC, IvanFesenko commented on src/style.css
> +}
You can just use `.fieldset`
```suggestion
.fieldset {
  margin-top: 20px;
}
```

2023-03-17 13:59 UTC, IvanFesenko commented on src/index.html
> +        </div>
Remove empty div

2023-03-17 13:59 UTC, IvanFesenko commented on src/style.css
> +}
Same here

2023-03-17 15:01 UTC, mykhalenych requested changes
check comments, also check tests you failed 7 tests

2023-03-17 15:01 UTC, mykhalenych commented on src/style.css
> +  font-family: Arial, Helvetica, sans-serif;
I think it is redundant, and don't see in requirements anything about font-family

2023-03-17 15:01 UTC, mykhalenych commented on src/index.html
> +              <option disabled selected>Chose</option>
delete it

2023-03-17 15:01 UTC, mykhalenych commented on src/index.html
> +              <option value="chevrolet">Chevrolet</option>
I see that on design
<img width="287" alt="Screenshot 2023-03-17 at 16 59 54" src="https://user-images.githubusercontent.com/53228259/225941818-cfe81f1b-7ca1-4898-9648-4370eef13a9f.png">

2023-04-25 10:30 UTC, anstsot requested changes
The code looks good but the tests are failed. could you please check them?
If you have any questions or troubles, feel free to ask them in the chat

2023-04-25 10:30 UTC, anstsot commented on src/style.css
> +}
these styles are redundant
```suggestion
```

2023-04-25 11:11 UTC, bohdanmayor commented on src/style.css
> +}
![изображение](https://user-images.githubusercontent.com/39329689/234259548-5440c502-9c29-4360-89c7-9b76d620daab.png)
all tests passed

2023-04-25 11:30 UTC, bohdanmayor commented on src/style.css
> +}
I understood, I have to change gh-pages (I have all tests passed localy, and terminal, but that file is old)

2023-04-25 12:13 UTC, bohdanmayor commented on src/style.css
> +}
Idk how to deploy, I have deploy error

2023-04-25 12:13 UTC, bohdanmayor commented on src/style.css
> +}
can you appruve it without gh-pages?

2023-04-25 15:15 UTC, mykhalenych requested changes
your links aren't working

2023-04-25 15:43 UTC, bohdanmayor commented
I know, i cant deploy pages

2023-04-25 16:02 UTC, closed without merging