Develop
mate-academy/layout_html-form pull request #582
Opened 2023-03-23 14:33 UTC by Alexkill667

- [DEMO LINK](https://Alexkill667.github.io/layout_html-form/)
- [TEST REPORT LINK](https://Alexkill667.github.io/layout_html-form/report/html_report/)

2023-03-23 14:37 UTC, qoa11a requested changes

2023-03-23 14:37 UTC, qoa11a commented on src/style.css
> +  /* margin-bottom: 20px; */
Remove comments.

2023-03-23 14:37 UTC, qoa11a commented on src/index.html
> +        <label class="none">
It's a bad class name. What does it represent?

2023-03-23 18:13 UTC, Alexkill667 commented on src/index.html
> +        <label class="none">
It's represent that this label is inline-block, because other labels are block

2023-03-23 18:17 UTC, Alexkill667 commented on src/style.css
> +  /* margin-bottom: 20px; */
Removed

2023-03-25 11:05 UTC, OleziO requested changes

2023-03-25 11:05 UTC, OleziO commented on src/index.html
> +            maxlength="3"
Dont need to use it here.

2023-03-25 11:05 UTC, OleziO commented on src/style.css
>  /* styles go here */
Remove comment.

2023-03-26 17:06 UTC, Alexkill667 commented on src/style.css
>  /* styles go here */
Removed

2023-03-26 17:07 UTC, Alexkill667 commented on src/index.html
> +            maxlength="3"
Removed

2023-03-26 17:48 UTC, witflash approved these changes
Well done 👍🏻

2023-09-15 20:08 UTC, closed without merging