add task solution - Layout-html-form
mate-academy/layout_html-form pull request #601
Opened 2023-03-29 20:54 UTC by Sadeni-09

- [DEMO LINK](https://Sadeni-09.github.io/layout_html-form/)
- [TEST REPORT LINK](https://Sadeni-09.github.io/layout_html-form/report/html_report/)

2023-03-30 09:12 UTC, anstsot requested changes
Good work. But please fix the issues according to the [checklist](https://github.com/mate-academy/layout_html-form/blob/master/checklist.md) and try to pass all tests.

2023-03-30 09:12 UTC, anstsot commented on src/index.html
> +      <div class="form-field">
add empty row between siblings
```suggestion
      <legend>Information:</legend>
      
      <div class="form-field">
```

2023-03-30 09:12 UTC, anstsot commented on src/index.html
> +    <fieldset>
the form should contain all fields
```suggestion
    <form action="http://localhost:8080/api" method="post">
      <fieldset>
```

2023-03-30 09:12 UTC, anstsot commented on src/index.html
> +          >
check the spacings
```suggestion
          <input
            type="text" 
            name="name" 
            required 
            autocomplete="off"
          >
```

2023-03-30 09:12 UTC, anstsot commented on src/index.html
> +        <label for="name">Name:
the child should start from new row
```suggestion
        <label for="name">
          Name:
```

2023-03-30 09:12 UTC, anstsot commented on src/style.css
> +  margin: 10px 0;
check the margins. you only need `margin-bottom`

2023-04-03 13:36 UTC, witflash requested changes
Well done! 👍 
Let's make the last syntax changes.

2023-04-03 13:36 UTC, witflash commented on src/index.html
> +            >
```suggestion
            <input 
              type="text" 
              name="surname" 
              autocomplete="off"
            >
```

2023-04-03 13:36 UTC, witflash commented on src/index.html
> +            >
```suggestion
            <input 
              type="text" 
              name="name" 
              required 
              autocomplete="off"
            >
```

2023-04-03 13:36 UTC, witflash commented on src/index.html
> +            >
```suggestion
          <label>
            How old are You?
            <input 
              type="number" 
              name="age" 
              value="12" 
              min="1" 
              max="100"
            >
```

2023-04-03 13:36 UTC, witflash commented on src/index.html
> +          </label>
```suggestion
          <label>
            Full date of birth:
            <input 
              type="date" 
              name="dateOfBirth" 
              value="mm/dd/yyyy"
            >
          </label>
```

2023-04-03 13:36 UTC, witflash commented on src/index.html
> +          </label>
```suggestion
          <label>
            I accept the term of the agreement
            <input type="checkbox" name="terms">
          </label>
```

2023-04-03 13:36 UTC, witflash commented on src/index.html
> +            >
```suggestion
          <label>
            E-mail:
            <input 
              type="email" 
              name="email" 
              placeholder="email@example.com" 
              required
            >
```

2023-04-03 13:36 UTC, witflash commented on src/index.html
> +          </label>
```suggestion
          <label>
            Password:
            <input 
              type="password" 
              name="password" 
              required
            >
          </label>
```

2023-04-03 13:36 UTC, witflash commented on src/index.html
> +        </div>
```suggestion
        <div class="form-field">
          Do you love cats?
          <label>
            <input type="radio" name="cat">
            Yes
          </label>
          <label>
            <input type="radio" name="cat">
            No
          </label>
        </div>
```

2023-04-03 13:36 UTC, witflash commented on src/index.html
> +            >
```suggestion
            <input 
              type="color" 
              name="color" 
              value="#000000"
            >
```

2023-04-03 13:36 UTC, witflash commented on src/index.html
> +          </label>
```suggestion
          <label>
            What time do you go to bed?
            <input 
              type="time" 
              name="timeToBed" 
              step="2"
            >
          </label>
```

2023-04-03 13:36 UTC, witflash commented on src/index.html
> +          </label>
```suggestion
          <label>
            How do you rate our work?
            <input 
              type="range" 
              name="rate" 
              min="0" 
              max="100"
              value="0"
            >
          </label>
```

2023-04-03 13:36 UTC, witflash commented on src/index.html
> +          </label>
```suggestion
          <label>
            Comments:
            <textarea 
              class="comment" 
              name="comments" 
              minlength="50" 
              maxlength="300"
            >
            </textarea>
          </label>
```

2023-04-03 13:36 UTC, witflash commented on src/index.html
> +          </label>
You may avoid using `for` attribule if your `label` is a wrapper for `input`.

2023-04-03 13:45 UTC, Sadeni-09 commented on src/index.html
> +          </label>
I didn't understand this, sorry. Where is "for"

2023-04-27 10:34 UTC, Anastasiia-Svintsova requested changes

2023-04-27 10:34 UTC, Anastasiia-Svintsova commented on src/index.html
> +    <form action="http://localhost:8080/api" method="post">
Follow the requirements, please. Don't use localhost in action
<img width="881" alt="image" src="https://user-images.githubusercontent.com/99403198/234836290-ff4f7bea-658b-4902-aaf2-a9a470e69781.png">

2023-04-27 10:34 UTC, Anastasiia-Svintsova commented on src/index.html
> +          <label for="surname">Surname:
Check the code style everywhere 
```suggestion
          <label for="surname">
            Surname:
```

2023-04-27 10:34 UTC, Anastasiia-Svintsova commented on src/index.html
> +        </div>
Why do you need additional div for each input? Remove them
```suggestion
          <label class="form-field">
            E-mail:
            <input 
              type="email" 
              name="email" 
              placeholder="email@example.com" 
              required
            >
          </label>
```

2023-04-27 10:34 UTC, Anastasiia-Svintsova commented on src/index.html
> +      <fieldset>
Don't forget to add empty lines between multiline sibling blocks of HTML
```suggestion
      </fieldset>
      
      <fieldset>
```

2023-04-27 10:34 UTC, Anastasiia-Svintsova commented on src/index.html
> +            </textarea>
Follow the code style from the checklist, please 
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/99403198/234837196-2849a299-0d21-4678-ab21-7d9aa71d7265.png">

2023-04-27 10:34 UTC, Anastasiia-Svintsova commented on src/index.html
> +      </div>
Same. Don't add additional wrappers everywhere 
```suggestion
        <button type="submit">Submit</button>
```

2023-04-27 10:34 UTC, Anastasiia-Svintsova commented on src/style.css
> +fieldset {
Don't style tags, use class selector instead

2023-05-01 19:29 UTC, closed without merging