html form
mate-academy/layout_html-form pull request #669
Opened 2023-04-10 15:35 UTC by olhry

2023-04-10 18:17 UTC, agniya-i requested changes
don't forget to copy DEMO LINK and TEST REPORT LINK from readme.md to the PR description

2023-04-10 18:17 UTC, agniya-i commented on src/style.css
> +.imput_margin {
```suggestion
.input_margin {
```

2023-04-10 18:17 UTC, agniya-i commented on src/index.html
> +            required
add `name` attribute

2023-04-10 18:17 UTC, agniya-i commented on src/index.html
> +
```suggestion
```

2023-04-10 18:17 UTC, agniya-i commented on src/index.html
> +          >
```suggestion
          <input
            type="time"
            name="time"
          >
```

2023-04-10 18:17 UTC, agniya-i commented on src/index.html
> +          >
```suggestion
          <input
            type="range"
            name="rate"
          >
```

2023-04-10 20:23 UTC, olhry commented on src/style.css
> +.imput_margin {
> виправив

2023-04-10 20:24 UTC, olhry commented
> Усі помилки вказані виправив. https://olhry.github.io/layout_html-form/report/html_report/

2023-04-10 20:34 UTC, olhry reviewed
Всі помилки виправлені

2023-04-10 20:34 UTC, olhry commented on src/index.html
> +            required
виправив

2023-04-10 20:34 UTC, olhry commented on src/index.html
> +
виправив

2023-04-10 20:34 UTC, olhry commented on src/index.html
> +          >
виправив

2023-04-10 20:34 UTC, olhry commented on src/index.html
> +          >
виправив

2023-04-11 07:23 UTC, tetiana-ivanchenko requested changes

2023-04-11 07:23 UTC, tetiana-ivanchenko commented on src/index.html
> +      name="html form">
```suggestion
    <form 
      action="https://mate-academy-form-lesson.herokuapp.com/create-application"
      method="post"
      name="html form"
    >
```

2023-04-11 07:23 UTC, tetiana-ivanchenko commented on src/index.html
> +      <!----------Registration -->
remove comments

2023-04-11 18:16 UTC, olhry commented on src/index.html
> +      name="html form">
changed

2023-04-11 18:16 UTC, olhry commented on src/index.html
> +      <!----------Registration -->
changed

2023-04-12 07:31 UTC, OleziO approved these changes

2024-04-05 21:36 UTC, closed without merging