adding 3 files
mate-academy/layout_html-form pull request #81
Opened 2023-01-17 14:03 UTC by oleh-stekh

DEMO LINK:https://oleh-stekh.github.io/layout_html-form/
TEST REPORT LINK:https://oleh-stekh.github.io/layout_html-form/report/html_report/

2023-01-17 15:32 UTC, mykhalenych requested changes

2023-01-17 15:32 UTC, mykhalenych commented on src/index.html
> +          <input
<img width="1292" alt="Screenshot 2023-01-17 at 17 24 24" src="https://user-images.githubusercontent.com/53228259/212938825-9bb7c37a-2018-4cb3-9709-7f38df8f868e.png">

2023-01-17 15:32 UTC, mykhalenych commented on src/index.html
> +          <input
check all elements

2023-01-17 15:32 UTC, mykhalenych commented on src/index.html
> +          required
why catLover is required?

2023-01-17 15:32 UTC, mykhalenych commented on src/index.html
> +        <label class="radioCatLovers">
use kebab-case for classnames

2023-01-17 15:32 UTC, mykhalenych commented on src/index.html
>      <script type="text/javascript" src="./main.js"></script>
better to add script in the end of body

2023-01-17 15:32 UTC, mykhalenych commented on src/style.css
> +  margin: auto auto 10px;
check styles you failed 6 tests

2023-01-20 11:48 UTC, witflash approved these changes
Well done 👍🏻

2023-12-27 13:19 UTC, closed without merging